### ISSUE TITLE
[meta] npm package name question

### ISSUE THREAD

**Issue by JounQin** [prettier/plugin-eslint#2]
@fisker @sosukesuzuki

I'd like to create a `prettier` plugin to run `eslint` inside, but the npm name [`prettier-plugin-eslint`](http://npmjs.com/prettier-plugin-eslint) is already taken, is that possible to use `@prettier/plugin-eslint` as the package name?

**Comment by fisker** [comment]
I don't know, we don't encourage plugins to modify AST, but this is what this plugin for. I guess it's not a good idea to use `@prettier/`.

**Comment by JounQin** [comment]
@fisker 

Well, in my view we don't need to encourage or discourage what a plugin does, and this will be a showcase how a prettier plugin could be, and I'd expected this new prettier plugin to replace [`prettier-eslint`](https://github.com/prettier/prettier-eslint) in the further, so that `prettier-eslint-cli` and [`vs-code-prettier-eslint`](https://github.com/idahogurl/vs-code-prettier-eslint) will just be unnecessary anymore. We will share the same plugin architecture and a single VSCode extension.

**Comment by JounQin** [comment]
Friendly ping @fisker @sosukesuzuki @thorn0

**Comment by JounQin** [comment]
I've just created a new npm org https://www.npmjs.com/org/prettier-eslint, if `@prettier/plugin-eslint` is not accepted, I'll publish it as `@prettier-eslint/prettier-plugin`.
